'use client';

import { Download, GitCompareArrows, Info, LineChart, MessageSquare, ShieldCheck } from 'lucide-react';

function formatDate(value) {
  return new Intl.DateTimeFormat(undefined, {
    month: 'short',
    day: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  }).format(new Date(value));
}

function escapeHtml(value) {
  return String(value)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');
}

function listItems(items) {
  return items.map((item) => `<li>${escapeHtml(item)}</li>`).join('');
}

function tableRows(entries) {
  return entries.map(([key, value]) => `<tr><th>${escapeHtml(key)}</th><td>${escapeHtml(value)}</td></tr>`).join('');
}

function buildReportHtml({ title, run, metrics, assumptions, transparency }) {
  const metricRows = metrics.map((metric) => [metric.label, metric.read(run)]);
  const sweepRows = run.sweep.map((point) => [
    point.label,
    Object.entries(point)
      .filter(([key]) => key !== 'label')
      .map(([key, value]) => `${key}: ${value}`)
      .join(', '),
  ]);

  return `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(title)} Report</title>
  <style>
    @page { margin: 18mm; }
    * { box-sizing: border-box; }
    body { color: #172033; font-family: Inter, Arial, sans-serif; line-height: 1.45; margin: 0; }
    header { border-bottom: 2px solid #2f63d7; margin-bottom: 24px; padding-bottom: 18px; }
    .eyebrow { color: #2f63d7; font-size: 11px; font-weight: 700; letter-spacing: 0.16em; text-transform: uppercase; }
    h1 { font-size: 30px; letter-spacing: -0.03em; margin: 8px 0 6px; }
    h2 { color: #23304a; font-size: 16px; margin: 24px 0 10px; }
    .meta { color: #526179; font-size: 12px; }
    .status { background: #eef4ff; border: 1px solid #c9d9ff; border-radius: 10px; color: #1d3d83; display: inline-block; font-weight: 700; margin-top: 12px; padding: 8px 12px; }
    table { border-collapse: collapse; width: 100%; }
    th, td { border-bottom: 1px solid #d9e1ef; font-size: 12px; padding: 9px 8px; text-align: left; vertical-align: top; }
    th { color: #526179; font-weight: 700; width: 42%; }
    ul { margin: 0; padding-left: 18px; }
    li { font-size: 12px; margin: 6px 0; }
    .grid { display: grid; gap: 18px; grid-template-columns: 1fr 1fr; }
    .panel { break-inside: avoid; }
    footer { border-top: 1px solid #d9e1ef; color: #66758d; font-size: 11px; margin-top: 28px; padding-top: 12px; }
    @media print { button { display: none; } }
  </style>
</head>
<body>
  <header>
    <div class="eyebrow">Phoenix Engine Engineering Report</div>
    <h1>${escapeHtml(title)}</h1>
    <div class="meta">Run ID: ${escapeHtml(run.id)} · Created: ${escapeHtml(formatDate(run.createdAt))}</div>
    <div class="status">${escapeHtml(run.outputs.status)}</div>
  </header>
  <main>
    <section class="grid">
      <div class="panel">
        <h2>Inputs</h2>
        <table>${tableRows(Object.entries(run.inputs))}</table>
      </div>
      <div class="panel">
        <h2>Results</h2>
        <table>${tableRows(metricRows)}</table>
      </div>
    </section>
    <section class="panel">
      <h2>Sensitivity Sweep</h2>
      <table>${tableRows(sweepRows)}</table>
    </section>
    <section class="grid">
      <div class="panel">
        <h2>Assumptions And Limitations</h2>
        <ul>${listItems(assumptions)}</ul>
      </div>
      <div class="panel">
        <h2>Model Transparency</h2>
        <ul>${listItems(transparency)}</ul>
      </div>
    </section>
  </main>
  <footer>Generated by Phoenix Engine. Save from the print dialog as PDF for sharing or design review.</footer>
  <script>window.addEventListener('load', () => setTimeout(() => window.print(), 150));</script>
</body>
</html>`;
}

export default function RunInsights({
  assumptions,
  chart,
  compareRun,
  disabled,
  metrics,
  onCompareRunChange,
  onDiscuss,
  run,
  runs,
  title,
  transparency,
}) {
  if (!run)
    return null;

  const chartPoints = chart.points(run);
  const maxChartValue = Math.max(...chartPoints.map((point) => Math.abs(point.value)), 1);

  const exportReport = () => {
    const reportWindow = window.open('', '_blank', 'width=960,height=720');
    if (!reportWindow)
      return;

    reportWindow.document.open();
    reportWindow.document.write(buildReportHtml({ title, run, metrics, assumptions, transparency }));
    reportWindow.document.close();
  };

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center gap-2">
        <button type="button" disabled={disabled} onClick={onDiscuss} className="flex items-center gap-1.5 rounded-lg bg-[#213550] px-3 py-1.5 text-xs text-[#aec8f3] hover:bg-[#28405f] disabled:opacity-50">
          <MessageSquare className="h-3.5 w-3.5" />
          Discuss in chat
        </button>
        <button type="button" onClick={exportReport} className="flex items-center gap-1.5 rounded-lg bg-[#1b3040] px-3 py-1.5 text-xs text-[#9edbd0] hover:bg-[#244155]">
          <Download className="h-3.5 w-3.5" />
          Export PDF
        </button>
      </div>

      <div className="rounded-xl border border-[#263a55] bg-[#0f1a2a]/72 p-4">
        <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.14em] text-[#789ee8]">
          <LineChart className="h-4 w-4" />
          {chart.title}
        </div>
        <div className="mt-4 space-y-3">
          {chartPoints.map((point) => (
            <div key={point.label} className="grid grid-cols-[minmax(88px,0.8fr)_minmax(0,1.8fr)_auto] items-center gap-3 text-xs text-[#b7c5d9]">
              <span className="truncate">{point.label}</span>
              <span className="h-2 overflow-hidden rounded-full bg-[#223550]">
                <span className="block h-full rounded-full bg-[linear-gradient(90deg,#4f7cf5,#56c1ff)]" style={{ width: `${Math.max(8, (Math.abs(point.value) / maxChartValue) * 100)}%` }} />
              </span>
              <span className="font-medium text-[#dee7f4]">{point.display}</span>
            </div>
          ))}
        </div>
      </div>

      {runs.length > 1 && (
        <div className="rounded-xl border border-[#263a55] bg-[#0f1a2a]/72 p-4">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.14em] text-[#789ee8]">
              <GitCompareArrows className="h-4 w-4" />
              Run comparison
            </div>
            <select
              value={compareRun?.id || ''}
              onChange={(event) => onCompareRunChange(event.target.value)}
              className="rounded-lg border border-[#30435d]/80 bg-[#19263a]/90 px-3 py-2 text-xs text-[#dce5f3] outline-none"
            >
              <option value="">Choose baseline</option>
              {runs.filter((candidate) => candidate.id !== run.id).map((candidate) => (
                <option key={candidate.id} value={candidate.id}>{formatDate(candidate.createdAt)}</option>
              ))}
            </select>
          </div>

          {compareRun ? (
            <div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
              {metrics.map((metric) => (
                <div key={metric.label} className="rounded-lg bg-[#142238] p-3">
                  <p className="text-xs text-[#8295b0]">{metric.label}</p>
                  <p className="mt-1 text-sm font-semibold text-[#edf3fb]">{metric.read(run)}</p>
                  <p className="mt-1 text-[11px] text-[#8fa1bb]">Baseline: {metric.read(compareRun)}</p>
                </div>
              ))}
            </div>
          ) : (
            <p className="mt-3 text-xs text-[#8fa1bb]">Select an older run to compare the current design candidate against a baseline.</p>
          )}
        </div>
      )}

      <div className="grid gap-4 lg:grid-cols-2">
        <details className="rounded-xl border border-[#263a55] bg-[#0f1a2a]/72 p-4 text-xs text-[#91a3bd]" open>
          <summary className="flex cursor-pointer items-center gap-2 text-[#aab9d0]">
            <ShieldCheck className="h-4 w-4 text-[#6de1b0]" />
            Assumption library
          </summary>
          <ul className="mt-3 list-disc space-y-1.5 pl-4">
            {assumptions.map((assumption) => <li key={assumption}>{assumption}</li>)}
          </ul>
        </details>

        <details className="rounded-xl border border-[#263a55] bg-[#0f1a2a]/72 p-4 text-xs text-[#91a3bd]" open>
          <summary className="flex cursor-pointer items-center gap-2 text-[#aab9d0]">
            <Info className="h-4 w-4 text-[#65c6ff]" />
            Model transparency
          </summary>
          <ul className="mt-3 list-disc space-y-1.5 pl-4">
            {transparency.map((item) => <li key={item}>{item}</li>)}
          </ul>
        </details>
      </div>
    </div>
  );
}
